name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal
          components: rustfmt,clippy
      - name: Build
        run: cargo build --all-features
      - name: Test
        run: cargo test
      - name: Clippy
        run: cargo clippy --all-features
      - name: Format check
        run: cargo fmt -- --check
